---
- name: Stat GeoIP City database file
  ansible.builtin.stat:
    path: /usr/share/GeoIP/GeoIPCity.dat
  register: geoip_city_database_result
- name: Update goaccess setting
  ansible.builtin.lineinfile:
    path: /etc/goaccess/goaccess.conf
    regexp: "^#?geoip-database "
    line: geoip-database /usr/share/GeoIP/GeoIPCity.dat
    create: true
  when: geoip_city_database_result.stat.exists
