---
- name: Service nginx is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true
- name: Ensure ufw is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: ufw
    state: started
    enabled: true
- name: Allow http and https port
  community.general.ufw:
    rule: allow
    name: WWW Full
