---
- name: Create/update config directories
  ansible.builtin.file:
    path: /etc/nginx/{{ item }}
    state: directory
    mode: "0755"
  loop:
    - conf.d
    - snippets
    - modules-available
    - modules-enabled
    - sites-available
    - sites-enabled
- name: Create/update nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: restart nginx
- name: Generate OpenSSL Diffie-Hellman parameters
  community.crypto.openssl_dhparam:
    path: "{{ nginx_dh_key_path }}"
    size: "{{ nginx_dh_key_bit }}"
  when: nginx_generate_dh_key
- name: Copy snippet files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/nginx/snippets/{{ item | basename }}
    mode: "0644"
  loop: "{{ lookup('fileglob', 'files/snippets/*.conf', wantlist=True) }}"
  loop_control:
    label: "{{ item | basename }}"
  notify: restart nginx
- name: Create nginx extra config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item[:-3] | basename }}
    mode: "0644"
  loop: "{{ lookup('fileglob', 'templates/conf/*.conf.j2', wantlist=True) }}"
  loop_control:
    label: "{{ item[:-3] | basename }}"
- name: Change extra config status
  ansible.builtin.file:
    path: /etc/nginx/modules-enabled/{{ item.name }}.conf
    src: "{{ item.state | default(true) | ternary('/etc/nginx/modules-available/' + item.name + '.conf', omit) }}"
    state: "{{ item.state | default(true) | ternary('link', 'absent') }}"
    mode: "0644"
  loop: "{{ nginx_modules }}"
  loop_control:
    label: "{{ item.name | default(item.server_name) }}"
  notify: restart nginx
- name: Create site config files
  ansible.builtin.template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/{{ item.name | default(item.server_name) }}
    mode: "0644"
  loop: "{{ nginx_vhosts }}"
  loop_control:
    label: "{{ item.name | default(item.server_name) }}"
  notify: restart nginx
- name: Change site config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/{{ item.name | default(item.server_name) }}
    src: "{{ item.state | default(true) | ternary('/etc/nginx/sites-available/' + item.name | default(item.server_name), omit) }}"
    state: "{{ item.state | default(true) | ternary('link', 'absent') }}"
    mode: "0644"
  loop: "{{ nginx_vhosts }}"
  loop_control:
    label: "{{ item.name | default(item.server_name) }}"
  notify: restart nginx
