---
nginx_cfg:
  extra_setting: |
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    map $geoip_country_code $allowed_country {
      default yes;
      CN no;
      RU no;
    }

## --------------
## バーチャルホストの設定
## --------------
nginx_vhosts:
  # --------------
  # Simple static site
  # --------------
  default:
    default_server: true
    server_name: example.com
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    document_root: /var/www/html
    index:
      - index.html
      - index.php
    ## 以下のホスト名でアクセスされた場合は「server_name」の値にリダイレクトさせる
    redirect_hosts:
      - www.example.com
    variables:
      var_name: var_value
    client_max_body_size: 20M
    includes:
      - snippets/letsencrypt_dehydrated.conf
    add_headers:
      X-custom-var: $var_name
      X-geoip-country-code: $geoip_country_code
      X-allowed-country: $allowed_country
    locations:
      - pattern: /favicon.ico
        content: |
          access_log off;
          log_not_found off;
      - pattern: /robots.txt
        content: |
          access_log off;
          log_not_found off;
      - pattern: /
        content: try_files $uri $uri/ =404;
      - pattern: /\.ht
        match_type: "~"
        content: |
          deny all;
  # --------------
  # status page
  # --------------
  status:
    server_name: localhost
    listen: 8080
    access_log: "off"
    locations:
      - pattern: /nginx_status
        content: |
          stub_status on;

## --------------
## ModSecurityを有効にする場合に読み込むルールファイル
## --------------
nginx_modsecurity_include_files:
  - /etc/modsecurity/crs/crs-setup.conf
  - /etc/modsecurity/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
  - /usr/share/modsecurity-crs/rules/*.conf
  - /etc/modsecurity/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
