---
nginx_append_goaccess_repository: false

nginx_cfg:
  extra_setting: |
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    map $geoip_country_code $allowed_country {
      default yes;
      CN no;
      RU no;
    }
