---
nginx_append_goaccess_repository: false

nginx_cfg:
  extra_setting: |
    geo $geo {
        default        0;
        127.0.0.1      2;
        192.168.0.0/16 1;
        172.16.0.0/12  1;
        10.1.0.0/8     1;
        ::1            2;
        2001:0db8::/32 1;
    }
    geoip_country /usr/share/GeoIP/GeoIP.dat;
    map $geoip_country_code $allowed_country {
      default yes;
      CN no;
      RU no;
    }
