---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    ## リポジトリのテスト
    - name: Test goaccess repository
      block:
        - name: Check apt source setting
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/goaccess.sources
          register: goaccess_repo_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - goaccess_repo_result.stat.exists
    ## パッケージのテスト
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nginx']
          - ansible_facts.packages['libnginx-mod-http-geoip']
          - ansible_facts.packages['goaccess']
    ## ユーザーのテスト
    - name: Check user
      ansible.builtin.user:
        name: www-data
        system: true
      check_mode: true
      register: result
    - name: Assert user
      ansible.builtin.assert:
        that:
          - result is not changed
    ## グループのテスト
    - name: Check group
      ansible.builtin.group:
        name: www-data
        system: true
      check_mode: true
      register: result
    - name: Assert group
      ansible.builtin.assert:
        that:
          - result is not changed
    # ファイルのテスト
    - name: Check virtualhost setting
      ansible.builtin.stat:
        path: /etc/nginx/sites-available/default
      register: result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - result.stat.exists
    - name: Check virtualhost enabled
      ansible.builtin.stat:
        path: /etc/nginx/sites-enabled/default
      register: result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - result.stat.exists
          - result.stat.islnk
          - result.stat.lnk_source == '/etc/nginx/sites-available/default'
    - name: Test load OWASP ModSecurity Core Rule Set
      when: ansible_facts.packages['libnginx-mod-http-modsecurity'] is defined
      block:
        - name: Check load OWASP ModSecurity Core Rule Set
          ansible.builtin.lineinfile:
            path: /etc/nginx/modsecurity_includes.conf
            line: include {{ item }}
          check_mode: true
          register: modsecurity_rule_file_included
          loop: "{{ nginx_modsecurity_include_files }}"
        - name: Assert load OWASP ModSecurity Core Rule Set
          ansible.builtin.assert:
            that:
              - modsecurity_rule_file_included is not changed
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['nginx.service']
          - ansible_facts.services['nginx.service']['state'] == 'running'
          - ansible_facts.services['nginx.service']['status'] == 'enabled'
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 80 in listen_tcp_posts
