---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    ## リポジトリのテスト
    - name: Test goaccess repository
      block:
        - name: Check apt source setting
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/goaccess.sources
          register: goaccess_repo_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - goaccess_repo_result.stat.exists
            fail_msg: "GoAccess repository source file not found"
            success_msg: "GoAccess repository source file exists"
    ## パッケージのテスト
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['nginx'] is defined
          - ansible_facts.packages['libnginx-mod-http-geoip'] is defined
          - ansible_facts.packages['goaccess'] is defined
        fail_msg: "Some required packages are not installed"
        success_msg: "All required packages are installed"
    ## ユーザーのテスト
    - name: Get user facts
      ansible.builtin.getent:
        database: passwd
        key: www-data
    - name: Assert user
      ansible.builtin.assert:
        that:
          - getent_passwd['www-data'] is defined
        fail_msg: "www-data user does not exist"
        success_msg: "www-data user exists"
    ## グループのテスト
    - name: Get group facts
      ansible.builtin.getent:
        database: group
        key: www-data
    - name: Assert group
      ansible.builtin.assert:
        that:
          - getent_group['www-data'] is defined
        fail_msg: "www-data group does not exist"
        success_msg: "www-data group exists"
    # ファイルのテスト
    - name: Check virtualhost setting
      ansible.builtin.stat:
        path: /etc/nginx/sites-available/default
      register: result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - result.stat.exists
        fail_msg: "nginx virtual host file not found"
        success_msg: "nginx virtual host file exists"
    - name: Check virtualhost enabled
      ansible.builtin.stat:
        path: /etc/nginx/sites-enabled/default
      register: result
    - name: Assert file
      ansible.builtin.assert:
        that:
          - result.stat.exists
          - result.stat.islnk
          - result.stat.lnk_source == '/etc/nginx/sites-available/default'
        fail_msg: "nginx virtual host symlink is not properly configured"
        success_msg: "nginx virtual host symlink is properly configured"
    - name: Test load OWASP ModSecurity Core Rule Set
      when: ansible_facts.packages['libnginx-mod-http-modsecurity'] is defined
      block:
        - name: Check load OWASP ModSecurity Core Rule Set
          ansible.builtin.lineinfile:
            path: /etc/nginx/modsecurity_includes.conf
            line: include {{ item }}
          check_mode: true
          register: modsecurity_rule_file_included
          loop: "{{ nginx_modsecurity_include_files }}"
        - name: Assert load OWASP ModSecurity Core Rule Set
          ansible.builtin.assert:
            that:
              - modsecurity_rule_file_included is not changed
            fail_msg: "OWASP ModSecurity Core Rule Set is not properly loaded"
            success_msg: "OWASP ModSecurity Core Rule Set is properly loaded"
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['nginx.service'] is defined
          - ansible_facts.services['nginx.service']['state'] == 'running'
          - ansible_facts.services['nginx.service']['status'] == 'enabled'
        fail_msg: "nginx service is not running or not enabled"
        success_msg: "nginx service is running and enabled"
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 80 in listen_tcp_posts
        fail_msg: "nginx is not listening on port 80"
        success_msg: "nginx is listening on port 80"
