---
nginx_packages:
  - nginx
  - goaccess
  - libnginx-mod-http-geoip
  - libnginx-mod-http-modsecurity
  - modsecurity-crs

## --------------
## バーチャルホストの設定
## --------------
nginx_vhosts:
  # --------------
  # Simple static site
  # --------------
  default:
    default_server: true
    server_name: example.com
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    document_root: /var/www/html
    index:
      - index.html
      - index.php
    ## 以下のホスト名でアクセスされた場合は「server_name」の値にリダイレクトさせる
    redirect_hosts:
      - www.example.com
    variables:
      var_name: var_value
    client_max_body_size: 20M
    includes:
      - snippets/letsencrypt_dehydrated.conf
      - snippets/modsecurity.conf
      # - /usr/share/modsecurity-crs/owasp-crs.load
    add_headers:
      X-custom-var: $var_name
      X-geoip-country-code: $geoip_country_code
      X-allowed-country: $geoip_country_code
      X-geo: $geo
    locations:
      - pattern: /favicon.ico
        content: |
          access_log off;
          log_not_found off;
      - pattern: /robots.txt
        content: |
          access_log off;
          log_not_found off;
      - pattern: /
        content: try_files $uri $uri/ =404;
      - pattern: \.php$
        match_type: "~"
        content: |
          include snippets/fastcgi-php.conf;
          fastcgi_pass unix:/run/php/php{{ php_version | default('8.2') }}-fpm.sock;
          # send_timeout 60s; # クライアントへの応答のタイムアウト時間
          # keepalive_timeout 60s; # クライアントとの接続をキープする時間
          # fastcgi_connect_timeout 60s; # nginxとphp-fpmの接続を確立するためのタイムアウト時間
          # fastcgi_send_timeout 60s; # nginxからphp-fpmへのリクエスト送信のタイムアウト時間
          # fastcgi_read_timeout 60s; # php-fpmからの応答のタイムアウト時間
      - pattern: /\.ht
        match_type: "~"
        content: |
          deny all;
